-- Create Demo Organization for Super Admin
INSERT INTO "Organization" (
    id,
    name,
    code,
    "fullName",
    address,
    city,
    province,
    "postalCode",
    country,
    email,
    phone,
    website,
    "logoUrl",
    "primaryColor",
    "secondaryColor",
    subdomain,
    plan,
    "maxUsers",
    "maxAthletes",
    "maxTeams",
    "isActive",
    "isTrial",
    "createdAt",
    "updatedAt"
) VALUES (
    '43c973a6-5e20-43af-a295-805f1d7c86b1',
    'Demo Soccer Club',
    'DEMO',
    'Demo Soccer Club ASD',
    'Via Demo 1',
    'Ravenna',
    'RA',
    '48121',
    'IT',
    'info@demosoccer.com',
    '+39 0544 123456',
    'https://demosoccer.com',
    'https://ui-avatars.com/api/?name=Demo+Soccer&background=3B82F6&color=fff&size=200&rounded=true&bold=true',
    '#3B82F6',
    '#1E40AF',
    'demo',
    'premium',
    100,
    500,
    20,
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    code = EXCLUDED.code,
    "fullName" = EXCLUDED."fullName",
    "logoUrl" = EXCLUDED."logoUrl",
    "primaryColor" = EXCLUDED."primaryColor",
    "secondaryColor" = EXCLUDED."secondaryColor",
    "isActive" = EXCLUDED."isActive",
    "updatedAt" = CURRENT_TIMESTAMP;

-- Verify
SELECT id, name, code, "isActive" FROM "Organization" WHERE id = '43c973a6-5e20-43af-a295-805f1d7c86b1';
